### ISSUE TITLE
Timeline slicer not selecting the last month

### ISSUE THREAD

**Issue by boltasdpoibi** [Microsoft/powerbi-visuals-timeline#20]
When all the months available for selection are selected, the last month is not selected even though it is available for selection.

Ppwer BI desktop version: 2.49.4831.521 64-bit (August 2017)
Timeline slicer version: 1.4.5.0

![screenshot](https://user-images.githubusercontent.com/31531745/29957728-a0d06db0-8f0c-11e7-8605-4c47603cffb2.png)

**Comment by boltasdpoibi** [comment]
Issue persists in Timeline slicer version 1.4.9

**Comment by uve** [comment]
Hello @boltasdpoibi, could you please send sample report to pbicvsupport@microsoft.com?
This issue should be fixed in 1.4.9

**Comment by boltasdpoibi** [comment]
I have shared the files using Dropbox.

**Comment by uve** [comment]
@boltasdpoibi, I've checked your sample report. New 1.4.9 version works fine to me.
![Sample image](http://rm.d.pr/MzKSkv)
Please note that 1.4.9 version will be available on prod Sep, 4.

**Comment by boltasdpoibi** [comment]
I am unable to view your sample image

**Comment by boltasdpoibi** [comment]
Can you please select all the months available and check. It is not selecting the last month only when all the months are selected.

**Comment by uve** [comment]
@boltasdpoibi, sure:
![Sample image](https://storage.googleapis.com/powerbi/timeline1.png)
![Sample image](https://storage.googleapis.com/powerbi/timeline2.png)

**Comment by boltasdpoibi** [comment]
Thank you very much. I have compiled the version 1.4.9 myself, which somehow did not resolve this issue for me. I will wait for the official version on the 4th.
