### ISSUE TITLE
Idea: Allow syncing of timeline across pages using 'Sync Slicers'

### ISSUE THREAD

**Issue by adam-wood** [Microsoft/powerbi-visuals-timeline#49]
With the '[Sync Slicers](https://docs.microsoft.com/en-us/power-bi/desktop-slicers)' feature, many slicers can be synced across pages. It would be great if we could somehow capture the Timeline slicer in this as well. Currently it is not possible to select Timeline objects with this feature.

**Comment by ignatvilesov** [comment]
`Sync Slicers` feature is already supported starting from `Timeline 2.0.1`.
