### ISSUE TITLE
Any resolution to the issue related to Timeline Slicer where it allows current period as default upon selection of property "Force Selection" but doesnt allow to reset the slicer when user trying to select other months.

### ISSUE THREAD

**Issue by santoshvejja** [Microsoft/powerbi-visuals-timeline#55]
Any resolution to the issue related to Timeline Slicer where it allows current period as default upon selection of property "Force Selection" but doesn't allow to reset the slicer when user trying to select other Periods.
what is the point of having default and not able to reset the default (interactivity) of the control .

**Comment by ignatvilesov** [comment]
The first solution we tried produced side issues. As a result we reverted a fix.

Currently we are investigating a different approach to fix it.

**Comment by ignatvilesov** [comment]
We merged PR that fixes this issue.

It will be released in around 3 weeks from now.

**Comment by ignatvilesov** [comment]
This is included into v[2.0.2](https://github.com/Microsoft/powerbi-visuals-timeline/releases/tag/2.0.2) that is going to be deployed on March 4th at 6 PM UTC.
