### ISSUE TITLE
Cannot Build visual after downloading and running pbiviz command

### ISSUE THREAD

**Issue by Kumar-Aakash** [microsoft/powerbi-visuals-timeline#62]
Hi

Thank you for the great library. I am trying to use it after downloading and running it on my local server for Developer visual.

After running **"pbiviz start"** command, it is giving me below error.

```
 info   Building visual...
 error  VALIDATION   Invalid API Version v2.5.0
```

As per other Git hub thread, I tried to run npm i and npm start commands but seems it is no help.

I also tried thread [https://github.com/Microsoft/PowerBI-visuals-tools/issues/242]() to fix it but still, it is giving me enough errors in the console. Something like this:

```
 info   Starting server...
 info   Start preparing plugin template
 error  error:0906D06C:PEM routines:PEM_read_bio:no start line
```

Any smooth process, steps to fix this issue?

Thanks in advance.

**Comment by pbicvsupport** [comment]
@aakash1401  Try to update powerbi-visuals-tools globally on your machine and then execute pbiviz update from inside visual's folder
