### ISSUE TITLE
BUG with the component Timeline Slicer & Power BI Report Server

### ISSUE THREAD

**Issue by mdurieux2** [microsoft/powerbi-visuals-timeline#70]
Hi !

Since I updated my Power BI Report Server and my Power BI Desktop with the september release, I can't use anymore the component Timeline Slicer.
It works perfectly with the desktop version (optimized for Report Server) but as soon as I publish my .pbix on Power BI Report Server, the visual timeline component appears but when I click on a date, it is not filtering my values in my table.

==> OK on Power BI Desktop
==> KO on Power BI Report Server

I use Power BI Report Server September 2019 / Power BI Desktop optimized for Report Server September and Timeline Visual 2.1.1.0.

Thanks for your help.

**Comment by helen508light** [comment]
Usually users have this problem when they try to use different versions with the same GUID. Please re-check is visual version u had attached right(in Desktop old version may be cached and updated to new one after re-installation\update).

**Comment by helen508light** [comment]
@mdurieux2
We'll add this issue to our backlog and fix in the next versions

**Comment by basstiekema** [comment]
> Hi !
> 
> Since I updated my Power BI Report Server and my Power BI Desktop with the september release, I can't use anymore the component Timeline Slicer.
> It works perfectly with the desktop version (optimized for Report Server) but as soon as I publish my .pbix on Power BI Report Server, the visual timeline component appears but when I click on a date, it is not filtering my values in my table.
> 
> ==> OK on Power BI Desktop
> ==> KO on Power BI Report Server
> 
> I use Power BI Report Server September 2019 / Power BI Desktop optimized for Report Server September and Timeline Visual 2.1.1.0.
> 
> Thanks for your help.

Same issue here! With Power BI Report Server September 2019.

Bas

**Comment by basstiekema** [comment]
> @mdurieux2
> We'll add this issue to our backlog and fix in the next versions

I don't hope you mean the next version of Power BI Report Server because that is in 3 months.

Bas

**Comment by basstiekema** [comment]
@mdurieux2 , Did you find an alternative?

**Comment by uve** [comment]
@basstiekema Power BI Report Server September 2019 has a bug with slicers. Please download an updated version publishedOctober, 10th. 
https://www.microsoft.com/en-us/download/details.aspx?id=57270
